### PR TITLE
Update source to ubuntu:focal

### LINKED ISSUE #24: bionic vs focal in Dockerfile
In the Dockerfile, i had success with bionic instead of focal on this line:

RUN echo "deb http://miktex.org/download/ubuntu focal universe" | tee /etc/apt/sources.list.d/miktex.list

With focal it threw an error about packages being held broken

### PR DESCRIPTION
**Pull request by PHPirates**
* Fixes a bug introduced with the partial update in fd73bc985b50f4f68b29f890f9200eafb493d73c
Fix #24

* For me, the build was hanging on an interactive prompt asking for the geographic area, so I fixed that as well. I think this is something that was not yet a problem on Bionic.

### CODE REVIEW

**Comment by RaphaelJenni** [comment]
Thank you for the fix @PHPirates. Workes for me. 

Deployed a version to docker hub in case anyone needs it. [`rjenni/miktex`](https://hub.docker.com/repository/docker/rjenni/miktex)

Hopefully, the official repo gets updated in the near future. @edocevoli ??

**Comment by PHPirates** [comment]
@edocevoli

**Comment by PHPirates** [comment]
@edocevoli

**Comment by PHPirates** [comment]
@edocevoli Please merge

**Comment by edocevoli** [comment]
Thank you for the PR. But please note that a merge has no effect at the moment, because automatic Docker builds are not enabled for the MiKTeX docker hub. I have to manually build the image and update it to the Docker registry.

**Comment by PHPirates** [comment]
@edocevoli It does have an effect in the sense that people can easily build the image themselves, without first being confused and then having to solve the problem manually every time. And it saves me having to try to keep a PR open just to advertise forks.
In the end, Docker hub is just for a little bit of extra convenience, though I would appreciate an update of course.

**Pull request closed without merging**
